export enum SocialMediaType {
    FACEBOOK = 'FACEBOOK',
    INSTAGRAM = 'INSTAGRAM',
    WEBSITE = 'WEBSITE',
    SOUNDCLOUD = 'SOUNDCLOUD',
    SPOTIFY = 'SPOTIFY',
    BEATPORT = 'BEATPORT',
    BANDCAMP = 'BANDCAMP',
    RESIDENT_ADVISOR = 'RESIDENT_ADVISOR',
}
