name: Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - '.prettierrc'
      - 'README.md'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Create environment files
        run: |
          mkdir -p src/environments
          echo "export const environment = {
            production: true,
            firebaseConfig: ${{ secrets.FIREBASE_CONFIG }}
          }" > src/environments/environment.ts

      - name: Install Dependencies
        run: |
          npm ci
          cd functions && npm ci

      - name: Run Tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Build Angular App
        run: npm run build --configuration=production

      - name: Build Functions
        working-directory: ./functions
        run: npm run build

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SECRET_ACCOUNT }}
